### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Ashhad1200** [MuhammadSoaleh/E-project#1]

**Comment by MuhammadSoaleh** [comment]
bhai group ma jo extract file dali ha bs usko C# ka format ma la ka ana ha mana kuch kam kiya ha kuch pages ready kar diya ha front end only git ma ha kam dekh lo

**Comment by Huzaifa-Salahuddin** [comment]
Bhai kaam kaha hai?

**Comment by MuhammadSoaleh** [comment]
Yar repository ma ha to

**Comment by MuhammadSoaleh** [comment]
Bass uska aga sa start kardo ap

**Comment by MuhammadSoaleh** [comment]
Master branch ma ha

**Comment by MuhammadSoaleh** [comment]
Or template Whatsapp group ma ha

**Comment by MuhammadSoaleh** [comment]
bhaiyo template set ap kam kardo kam nhi rokna ab
