### ISSUE TITLE
Admin Panal

### ISSUE THREAD

**Issue by Ashhad1200** [MuhammadSoaleh/E-project#4]

**Comment by MuhammadSoaleh** [comment]
uzair yar admin wala kam karla jaldi taka models wala kam clear ho jai

**Comment by MuhammadSoaleh** [comment]
ashad yar tum sara cards ko dekh lo  home services portfolio ma ha agar or jagha ha to usa bhi set karlo phir services ma right side ma Features hai woh bhi database sa ainga

**Comment by MuhammadSoaleh** [comment]
kiya admin wala kam?
kam roka hoa ha tumhara chakar ma
